export const TableData: Array<any> = [
    {
        "doctor_id": "622001",
        "name": "Dr. Shivam Gupta",
        "email_id": "shivam.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "ENT",
        "qualification": "MBBS, MS",
    },
    {
        "doctor_id": "622002",
        "name": "Dr. Amal Krishna",
        "email_id": "Amal.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Gynaceologist",
        "qualification": "MBBS, MD",
    },
    {
        "doctor_id": "622003",
        "name": "Dr. Ajay Mishra",
        "email_id": "ajay.m17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Heart Specialist",
        "qualification": "MBBS MD",
    },
    {
        "doctor_id": "622004",
        "name": "Dr. Aman Kumar",
        "email_id": "aman.k17",
        "mobile_no": 9411329082,
        "speciality": "ENT",
        "qualification": "MBBS",
    },
    {
        "doctor_id": "622005",
        "name": "Dr. Aman Gupta",
        "email_id": "aman.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Gynaceologist",
        "qualification": "MBBS, MD, MS",
    },
    {
        "doctor_id": "622006",
        "name": "Dr. Shivankar Gupta",
        "email_id": "shivan.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "EYE SPECIALIST",
        "qualification": "MBBS MD",
    },
    {
        "doctor_id": "622007",
        "name": "Dr. Shivam Shekar",
        "email_id": "shivam.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "ENT",
        "qualification": "MBBS MS",
    },
    {
        "doctor_id": "622008",
        "name": "Dr. Ashish Kartha",
        "email_id": "Ashish.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Gynaceologist",
        "qualification": "MBBS, MD, MS",
    },
    {
        "doctor_id": "622009",
        "name": "Dr. Matthew Fleishman",
        "email_id": "Matthew.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Diagnostic Radiology",
        "qualification": "MBBS MD",
    },
    {
        "doctor_id": "622010",
        "name": "Dr. A.Indra",
        "email_id": "Indra.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Paediatrics & Neonatology",
        "qualification": "MBBS, MD, DM",
    },
    {
        "doctor_id": "622011",
        "name": "Dr. Abdul Salam C K",
        "email_id": "Abdul.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Casualty Medical Officer",
        "qualification": "MBBS",
    },      
    {
        "doctor_id": "622012",
        "name": "Dr. Anubhav Goyal",
        "email_id": "Anubhav.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Ophthalmology",
        "qualification": "MBBS, MD",
    },
    {
        "doctor_id": "622013",
        "name": "Dr. C.N.Mohan Nair",
        "email_id": "Dinesh.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Oncology",
        "qualification": "MBBS MD",
    },
    {
        "doctor_id": "622014",
        "name": "Dr. Antony Thatchil",
        "email_id": "Antony.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "General Medicine",
        "qualification": "MBBS, MD",
    },
    {
        "doctor_id": "622015",
        "name": "Dr. Antony Thatchil",
        "email_id": "Antony.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "General Medicine",
        "qualification": "MBBS, MD",
    },
    {
        "doctor_id": "622016",
        "name": "Dr. Joby Abraham",
        "email_id": "Joby.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "General Surgery",
        "qualification": "MBBS, MS",
    },
    {
        "doctor_id": "622017",
        "name": "Dr. K.N.Prakasam",
        "email_id": "KNPrakasam.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Dermatology",
        "qualification": "MBBS",
    },
    {
        "doctor_id": "622018",
        "name": "Dr. Aju Mathew",
        "email_id": "Aju.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Oncology",
        "qualification": "MBBS MD, MPhil, FACP",
    },
    {
        "doctor_id": "622019",
        "name": "Dr. P.N. Dinesh Kamath",
        "email_id": "Dinesh.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Neurology",
        "qualification": "MBBS",
    },
    {
        "doctor_id": "622020",
        "name": "Dr. Nasser Yusuf",
        "email_id": "NasserY.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Thoracic Surgery",
        "qualification": "MBBS, MS, MCh in Cardiothoracic Surgery",
    },
    {
        "doctor_id": "622021",
        "name": "Dr. P.N. Dinesh Kamath",
        "email_id": "Dinesh.g17@iiits.in",
        "mobile_no": 9411329082,
        "speciality": "Neurology",
        "qualification": "MBBS",
    },	    
   
  	
]